language: ruby

bundler_args: '--with=development --jobs=3 --retry=3 --verbose'

rvm:
  - 2.2.4

sudo: false

cache:
  bundler: true

git:
  depth: 15

notifications:
  email: false

script: bundle exec rspec spec/

matrix:
  fast_finish: true
